In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import edward as ed
import numpy as np
import tensorflow as tf
from keras import datasets
from keras.utils import np_utils

from edward.models import Normal

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def build_toy_dataset(N, w):
    D = len(w)
    x = np.random.normal(0.0, 2.0, size=(N, D))
    y = np.dot(x, w) + np.random.normal(0.0, 0.05, size=N)
    return x, y

N = 10000  # size of training data
M = 128    # batch size during training
D = 10     # number of features

w_true = np.ones(D) * 5
X_train, y_train = build_toy_dataset(N, w_true)
X_test, y_test = build_toy_dataset(235, w_true)

In [3]:
def generator(arrays, batch_size):
    starts = [0] * len(arrays)  # pointers to where we are in iteration
    while True:
        batches = []
        for i, array in enumerate(arrays):
            start = starts[i]
            stop = start + batch_size
            diff = stop - array.shape[0]
            if diff <= 0:
                batch = array[start:stop]
                starts[i] += batch_size
            else:
                batch = np.concatenate((array[start:], array[:diff]))
                starts[i] = diff
            batches.append(batch)
    yield batches

data = generator([X_train, y_train], M)

In [4]:
X = tf.placeholder(tf.float32, [None, D])
y_ph = tf.placeholder(tf.float32, [None])

w = Normal(loc=tf.zeros(D), scale=tf.ones(D))
b = Normal(loc=tf.zeros(1), scale=tf.ones(1))
y = Normal(loc=ed.dot(X, w) + b, scale=1.0)

In [5]:
qw = Normal(loc=tf.get_variable("qw/loc", [D]),
            scale=tf.nn.softplus(tf.get_variable("qw/scale", [D])))
qb = Normal(loc=tf.get_variable("qb/loc", [1]),
            scale=tf.nn.softplus(tf.get_variable("qb/scale", [1])))

In [10]:
int(N/M)

78

In [12]:
inference.n_iter//10

78

In [9]:
n_batch = int(N / M)
n_epoch = 5

inference = ed.KLqp({w: qw, b: qb}, data={y: y_ph})
inference.initialize(n_iter=n_batch * n_epoch, 
                     n_samples=5, scale={y: N / M})
tf.global_variables_initializer().run()

In [12]:
for _ in range(inference.n_iter):
    X_batch, y_batch = next(data)
    info_dict = inference.update({X: X_batch, y_ph: y_batch})
    inference.print_progress(info_dict)

In [11]:
inference.n_iter # 78*5

390

In [13]:
n_batch = int(N / M)
n_epoch = 1

inference = ed.KLqp({w: qw, b: qb}, data={y: y_ph})
inference.initialize(n_iter=n_batch * n_epoch * 10, 
                     n_samples=5, scale={y: N / M})
tf.global_variables_initializer().run()
for _ in range(inference.n_iter // 10):
    X_batch, y_batch = next(data)
    for _ in range(10):
        info_dict = inference.update({X: X_batch, y_ph: y_batch})

    inference.print_progress(info_dict)

In [14]:
inference.n_iter # 78*1*10

780

In [ ]:
for _ in range(inference.n_iter // 10):
    X_batch, y_batch = next(data)
    for _ in range(10):
        info_dict = inference.update({X: X_batch, y_ph: y_batch})

    inference.print_progress(info_dict)

In [39]:
random.seed(10)

In [ ]:
()

In [47]:
kk[1]

array([[[154, 177, 187],
        [126, 137, 136],
        [105, 104,  95],
        ...,
        [ 91,  95,  71],
        [ 87,  90,  71],
        [ 79,  81,  70]],

       [[140, 160, 169],
        [145, 153, 154],
        [125, 125, 118],
        ...,
        [ 96,  99,  78],
        [ 77,  80,  62],
        [ 71,  73,  61]],

       [[140, 155, 164],
        [139, 146, 149],
        [115, 115, 112],
        ...,
        [ 79,  82,  64],
        [ 68,  70,  55],
        [ 67,  69,  55]],

       ...,

       [[175, 167, 166],
        [156, 154, 160],
        [154, 160, 170],
        ...,
        [ 42,  34,  36],
        [ 61,  53,  57],
        [ 93,  83,  91]],

       [[165, 154, 128],
        [156, 152, 130],
        [159, 161, 142],
        ...,
        [103,  93,  96],
        [123, 114, 120],
        [131, 121, 131]],

       [[163, 148, 120],
        [158, 148, 122],
        [163, 156, 133],
        ...,
        [143, 133, 139],
        [143, 134, 142],
        [143, 133, 144]]

In [29]:
Y_batch

[array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)]

In [42]:
X_batch, Y_batch = random.sample(kk,2), random.sample(k,2)

In [43]:
Y_batch[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [44]:
X_batch[1]

array([[[154, 177, 187],
        [126, 137, 136],
        [105, 104,  95],
        ...,
        [ 91,  95,  71],
        [ 87,  90,  71],
        [ 79,  81,  70]],

       [[140, 160, 169],
        [145, 153, 154],
        [125, 125, 118],
        ...,
        [ 96,  99,  78],
        [ 77,  80,  62],
        [ 71,  73,  61]],

       [[140, 155, 164],
        [139, 146, 149],
        [115, 115, 112],
        ...,
        [ 79,  82,  64],
        [ 68,  70,  55],
        [ 67,  69,  55]],

       ...,

       [[175, 167, 166],
        [156, 154, 160],
        [154, 160, 170],
        ...,
        [ 42,  34,  36],
        [ 61,  53,  57],
        [ 93,  83,  91]],

       [[165, 154, 128],
        [156, 152, 130],
        [159, 161, 142],
        ...,
        [103,  93,  96],
        [123, 114, 120],
        [131, 121, 131]],

       [[163, 148, 120],
        [158, 148, 122],
        [163, 156, 133],
        ...,
        [143, 133, 139],
        [143, 134, 142],
        [143, 133, 144]]

In [40]:
k = [np.reshape(sess.run(y_train),(-1,10))[0],np.reshape(sess.run(y_train),(-1,10))[1],np.reshape(sess.run(y_train),(-1,10))[2],np.reshape(sess.run(y_train),(-1,10))[3]]

In [41]:
kk = [x_train[0],x_train[1],x_train[2],x_train[3]]

In [ ]:
X_batch, Y_batch = random.sample(list(x_train),N), random.sample(list(np.reshape(sess.run(y_train),(-1,10))),N)

In [15]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from edward.models import Categorical, Normal
import edward as ed
import random


# CIFAR-10 데이터를 다운로드 받기 위한 helpder 모듈인 load_data 모듈을 임포트합니다.
from tensorflow.python.keras._impl.keras.datasets.cifar10 import load_data

# CIFAR-10 데이터를 다운로드하고 데이터를 불러옵니다.
(x_train, y_train), (x_test, y_test) = load_data()

# parameters
N = 256   # number of images in a minibatch.


# Create a placeholder to hold the data (in minibatches) in a TensorFlow graph.
x = tf.placeholder(tf.float32, [None, 32, 32, 3])

# Normal(0,1) priors for the variables. Note that the syntax assumes TensorFlow 1.1.
w1 = Normal(loc=tf.zeros([3, 3, 3, 32]), scale=tf.ones([3, 3, 3, 32]))
l1 = tf.nn.conv2d(x, w1, strides=[1, 1, 1, 1], padding='SAME')
l1 = tf.nn.relu(l1)
l1 = tf.nn.max_pool(l1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

w2 = Normal(loc=tf.zeros([3, 3, 32, 64]), scale=tf.ones([3, 3, 32, 64]))
l2 = tf.nn.conv2d(l1, w2, strides=[1, 1, 1, 1], padding='SAME')
l2 = tf.nn.relu(l2)
l2 = tf.nn.max_pool(l2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

w3 = Normal(loc=tf.zeros([3, 3, 64, 128]), scale=tf.ones([3, 3, 64, 128]))
l3 = tf.nn.conv2d(l2, w3, strides=[1, 1, 1, 1], padding='SAME')
l3 = tf.nn.relu(l3)
l3 = tf.nn.max_pool(l3, ksize=[1, 2, 2, 1], strides=[ 1, 2, 2, 1], padding='SAME')

l3_flat = tf.reshape(l3, [-1, 128 * 4 * 4])

w4 = Normal(loc=tf.zeros([128 * 4 * 4, 625]), scale=tf.ones([128 * 4 * 4, 625]))
b4 = Normal(loc=tf.zeros(625), scale=tf.ones(625))
l4 = tf.nn.relu(tf.matmul(l3_flat, w4) + b4)

w5 = Normal(loc=tf.zeros([625, 10]), scale=tf.ones([625, 10]))
b5 = Normal(loc=tf.zeros(10), scale=tf.ones(10))

# Categorical likelihood for classication.
y = Categorical(tf.matmul(l4,w5)+b5)

# Contruct the q(w) and q(b). in this case we assume Normal distributions.
qw1 = Normal(loc=tf.Variable(tf.random_normal([3, 3, 3, 32])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([3, 3, 3, 32]))))
qw2 = Normal(loc=tf.Variable(tf.random_normal([3, 3, 32, 64])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([3, 3, 32, 64]))))
qw3 = Normal(loc=tf.Variable(tf.random_normal([3, 3, 64, 128])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([3, 3, 64, 128]))))
qw4 = Normal(loc=tf.Variable(tf.random_normal([128 * 4 * 4, 625])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([128 * 4 * 4, 625]))))       
qw5 = Normal(loc=tf.Variable(tf.random_normal([625, 10])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([625, 10]))))
qb4 = Normal(loc=tf.Variable(tf.random_normal([625])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([625]))))
qb5 = Normal(loc=tf.Variable(tf.random_normal([10])),
              scale=tf.nn.softplus(tf.Variable(tf.random_normal([10]))))

y_train = tf.one_hot(y_train, 10)
y_test = tf.one_hot(y_test, 10)

# We use a placeholder for the labels in anticipation of the traning data.
y_ph = tf.placeholder(tf.int32, [N])
# Define the VI inference technique, ie. minimise the KL divergence between q and p.
inference = ed.KLqp({w1: qw1, w2: qw2, w3: qw3, w4: qw4, w5: qw5,
                     b4: qb4, b5: qb5 }, data={y:y_ph})

# Initialse the infernce variables
inference.initialize(n_iter=N, n_print=1, scale={y: float(len(x_train) / N)})

# We will use an interactive session.
sess = tf.InteractiveSession()
# Initialise all the vairables in the session.
tf.global_variables_initializer().run()

# Let the training begin. We load the data in minibatches and update the VI infernce using each new batch.
for _ in range(inference.n_iter):
    X_batch, Y_batch = random.sample(list(x_train),N), random.sample(list(np.reshape(sess.run(y_train),(-1,10))),N)
    # TensorFlow method gives the label data in a one hot vetor format. We convert that into a single label.
    Y_batch = np.argmax(Y_batch,axis=1)
    info_dict = inference.update(feed_dict={x: X_batch, y_ph: Y_batch})
    inference.print_progress(info_dict)


# Load the test images.
X_test = tf.convert_to_tensor(x_test,dtype=tf.float32)
# TensorFlow method gives the label data in a one hot vetor format. We convert that into a single label.
Y_test = np.argmax(np.reshape(sess.run(y_test),(-1,10)),axis=1)

# Generate samples the posterior and store them.
n_samples = 5
prob_lst = []
for i in range(n_samples):
    w1_samp = tf.convert_to_tensor(qw1.sample(),dtype=tf.float32)
    w2_samp = tf.convert_to_tensor(qw2.sample(),dtype=tf.float32)
    w3_samp = tf.convert_to_tensor(qw3.sample(),dtype=tf.float32)
    w4_samp = tf.convert_to_tensor(qw4.sample(),dtype=tf.float32)
    w5_samp = tf.convert_to_tensor(qw5.sample(),dtype=tf.float32)
    b4_samp = qb4.sample()
    b5_samp = qb5.sample()
    # Also compue the probabiliy of each class for each (w,b) sample.

    l1_samp = tf.nn.conv2d(X_test, w1_samp, strides=[1, 1, 1, 1], padding='SAME')
    l1_samp = tf.nn.relu(l1_samp)
    l1_samp = tf.nn.max_pool(l1_samp, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

    l2_samp = tf.nn.conv2d(l1_samp, w2_samp, strides=[1, 1, 1, 1], padding='SAME')
    l2_samp = tf.nn.relu(l2_samp)
    l2_samp = tf.nn.max_pool(l2_samp, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

    l3_samp = tf.nn.conv2d(l2_samp, w3_samp, strides=[1, 1, 1, 1], padding='SAME')
    l3_samp = tf.nn.relu(l3_samp)
    l3_samp = tf.nn.max_pool(l3_samp, ksize=[1, 2, 2, 1], strides=[ 1, 2, 2, 1], padding='SAME')

    l3_flat_samp = tf.reshape(l3_samp, [-1, 128 * 4 * 4])

    l4_samp = tf.nn.relu(tf.matmul(l3_flat_samp, w4_samp) + b4_samp)

    l5_samp = tf.matmul(l4_samp,w5_samp)+b5_samp

    prob = tf.nn.softmax(l5_samp)
    prob_lst.append(prob.eval())
    print(i+1, "steps completed.")


# Compute the accuracy of the model. 
# For each sample we compute the predicted class and compare with the test labels.
# Predicted class is defined as the one which as maximum proability.
# We perform this test for each (w,b) in the posterior giving us a set of accuracies
# Finally we make a histogram of accuracies for the test data.
accy_test = []
for prob in prob_lst:
    y_trn_prd = np.argmax(prob,axis=1).astype(np.float32)
    acc = (y_trn_prd == Y_test).mean()
    accy_test.append(acc)

print("Expactation of Accuracy: ", sess.run(tf.reduce_mean(accy_test)))

plt.hist(accy_test)
plt.title("Histogram of prediction accuracies in the MNIST test data")
plt.xlabel("Accuracy")
plt.ylabel("Frequency")
plt.show()

  3/256 [  1%]                                ETA: 487s | Loss: 104736401391616.000

KeyboardInterrupt: 